name: shit_grabber
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.3.8
  cupertino_icons: ^1.0.3
  path_provider: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  pedantic: ^1.11.1
  effective_dart: ^1.3.2
  analyzer: ^2.6.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - fonts/
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/SpaceMono-Regular.ttf
        - asset: fonts/SpaceMono-Bold.ttf
        - asset: fonts/SpaceMono-Italic.ttf
        - asset: fonts/SpaceMono-BoldItalic.ttf
